### ISSUE TITLE
Tx/Rx Over IP traffic  between two machines without Radio

### ISSUE THREAD

**Issue by AravindkannanCT** [aff3ct/dvbs2#6]
Hello, i am interested in the aff3ct Dvbs2 package, and i was wondering, if its possible to establish IP traffic between two different machines which are in the same network using the aff3ct dvbs2 and without Radio? Can i use something similar to virtual radio like ZeroMQ ?

Thanks.

**Comment by kouchy** [comment]
Hi @AravindkannanCT,

It sounds doable to me. I think you could inherit from the [Radio class](https://github.com/aff3ct/dvbs2/blob/master/src/common/Module/Radio/Radio.hpp) to encapsulate IP input en output traffic in the `send` and `receive` methods.

**Comment by AravindkannanCT** [comment]
I will check this. thanks.
